
## Importing the datasets


In [91]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 


## Importing the datasets


In [92]:

ds = pd.read_csv('Social_network_ads.csv')
x = ds.iloc[: , : -1].values
y = ds.iloc[ : , -1].values




##  Splitting the datasets into test_sets and train_sets


In [93]:

from sklearn.model_selection import train_test_split
train_x , test_x ,train_y , test_y = train_test_split(x , y  , test_size = 0.2 , random_state = 0)
 


## Feature scaling


In [94]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)


## Creating the naive model and training it 


In [95]:

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(train_x , train_y)


GaussianNB()


## Predicting a single result 


In [96]:

classifier.predict(sc.fit_transform([[19,76000]]))


array([0], dtype=int64)

In [97]:
pred_y = classifier.predict(test_x)


## Prediciting the test sets


In [98]:
print(np.concatenate((pred_y.reshape(len(pred_y),1) , test_y.reshape(len(test_y) , 1)) ,1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]



## Confusion matrix and accuracy score



In [99]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(test_y , pred_y)
print(cm)
accuracy_score(test_y , pred_y)

[[55  3]
 [ 4 18]]


0.9125


## k-fold (cross validation) for better prediction


In [100]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator = classifier ,X = train_x ,y = train_y , cv =10)
print('ACcuracy : {:.2f}%'.format(accuracy.mean()*100))
print('Standard Deviation : {:.2f}%'.format(accuracy.std()*100))

ACcuracy : 86.56%
Standard Deviation : 8.03%
