## installing the libararies

In [48]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as  pd

## installing the datasets 

In [49]:
ds = pd.read_csv('Social_Network_Ads.csv')
x = ds.iloc[ : ,  : -1].values
y = ds.iloc[ : , -1].values

## splitting the datasets

In [50]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y , test_y = train_test_split(x , y ,test_size = 0.2 , random_state = 0)

## feature scaling

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

## creating and training the model

In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy'  , random_state = 0)
classifier.fit(train_x , train_y)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)


## predicitng a single value


In [53]:
classifier.predict(sc.transform([[32, 18000]]))


array([0], dtype=int64)

## predicting the whole test set

In [54]:
pred_y = classifier.predict(test_x)
print(np.concatenate((pred_y.reshape(len(pred_y),1) , test_y.reshape(len(test_y) , 1)) ,1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


## confusion matriz and accuracy score

In [55]:
from sklearn.metrics import accuracy_score , confusion_matrix
cm = confusion_matrix(test_y , pred_y )
print(cm)
accuracy_score(test_y , pred_y)

[[54  4]
 [ 3 19]]


0.9125

In [56]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier , X = train_x, y = train_y )
print('Accuracies : {:.2f}%'.format(accuracies.mean()*100))
print('Standard deviation : {:.2f}%'.format(accuracies.std()*100))

Accuracies : 88.12%
Standard deviation : 3.37%
