
## Importing the libararies


In [91]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 


## Importing the datasets


In [92]:
ds = pd.read_csv('Social_Network_Ads.csv')
x = ds.iloc[ : , : -1].values
y = ds.iloc[  :, -1].values



## splitting the dataset into test set and train sets 


In [93]:
from sklearn.model_selection import train_test_split
train_x, test_x , train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0)


## Feature Scaling


In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)


## creating an SVM model and training the data sets


In [95]:

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear' , random_state = 0 )
classifier.fit(train_x , train_y)

SVC(kernel='linear', random_state=0)


## Predicting a single value


In [96]:
classifier.predict([[32,18000]])


array([1], dtype=int64)


## Predicting the test results


In [97]:

y_pred = classifier.predict(test_x)
print(np.concatenate((y_pred.reshape(len(y_pred) , 1) , test_y.reshape(len(test_y) , 1 ) ) , 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]]



## Confusion matrix and checking the accuracy


In [98]:
from sklearn.metrics import accuracy_score , confusion_matrix
cm = confusion_matrix(test_y , y_pred)
print(cm)
print(accuracy_score(test_y , y_pred))

[[57  1]
 [ 6 16]]
0.9125



##  K fold method for better accuracy


In [99]:
from sklearn.model_selection import cross_val_score
accuracy = cross_val_score(estimator = classifier , X = train_x , y = train_y , cv =10)
print('Accuracy : {:.2f}%'.format(accuracy.mean()*100))
print('Standard Deviation : {:.2f}%'.format(accuracy.std()*100))

Accuracy : 81.88%
Standard Deviation : 10.16%
